# Site settings
title: Codesnik's snippets
email: aronaxis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Alexey "codesnik" Trofimenko, I'm a software engineer from Moscow, Russia. Here you'll find random thoughts and code snippets I sincerely hope could be useful for developers like me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://codesnik.github.io" # the base hostname & protocol for your site
twitter_username: codesnik
github_username:  codesnik

# Build settings
markdown: kramdown
